# Generated by Django 6.0.1 on 2026-02-05 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customerpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappchat',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='whatsappchat',
            name='media_url',
        ),
        migrations.RemoveField(
            model_name='whatsappchat',
            name='message_type',
        ),
        migrations.RemoveField(
            model_name='whatsappchat',
            name='synced_at',
        ),
        migrations.RemoveField(
            model_name='whatsappchat',
            name='whatsapp_message_id',
        ),
        migrations.AddField(
            model_name='whatsappchat',
            name='direction',
            field=models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='whatsappchat',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='WhatsAppLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('user_type', models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer'), ('enquiry', 'General Enquiry'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('gst_status', models.CharField(choices=[('none', 'Not Checked'), ('pending', 'Pending Input'), ('verified', 'Verified'), ('failed', 'Verification Failed'), ('no_gst', 'User has no GST')], default='none', max_length=20)),
                ('conversation_stage', models.CharField(default='W-001', max_length=50)),
                ('needs_human', models.BooleanField(default=False)),
                ('last_message_time', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_state', to='core.customer')),
            ],
        ),
    ]
