# Generated by Django 6.0.1 on 2026-02-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customer_company_name_customer_gst_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_gst_verified',
            field=models.BooleanField(default=False, help_text='True if verified via WhatsApp or Manually by Employee'),
        ),
    ]
