# Generated by Django 6.0.1 on 2026-05-12 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='hostinger_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.customer'),
        ),
    ]
