# Generated by Django 6.0.1 on 2026-05-30 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_attendance_ip_address_attendance_is_late_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('current_address', models.TextField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('institution', models.CharField(blank=True, max_length=100, null=True)),
                ('passing_year', models.CharField(blank=True, max_length=10, null=True)),
                ('previous_company', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('aadhar_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('pan_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('other_document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('family_members_json', models.JSONField(blank=True, default=list)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('previous_month_salary_slip', models.FileField(blank=True, null=True, upload_to='salary_slips/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
