# Generated by Django 6.0.1 on 2026-07-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_break_break_type_loginapprovalrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
