# Generated by Django 6.0.1 on 2026-07-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_attendance_current_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapplead',
            name='business_type',
            field=models.CharField(blank=True, choices=[('manufacturer', 'Manufacturer'), ('brand_owner', 'Brand Owner'), ('distributor', 'Distributor'), ('wholesaler', 'Wholesaler'), ('retailer', 'Retailer'), ('others', 'Others')], max_length=50, null=True),
        ),
    ]
