# Generated by Django 6.0.1 on 2026-07-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_whatsapplead_business_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wamid', models.CharField(db_index=True, max_length=255)),
                ('recipient_id', models.CharField(db_index=True, max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=20, null=True)),
                ('error_title', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('conversation_category', models.CharField(blank=True, max_length=50, null=True)),
                ('pricing_billable', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['recipient_id', 'status'], name='core_whatsa_recipie_ec250f_idx'), models.Index(fields=['wamid'], name='core_whatsa_wamid_2be070_idx')],
            },
        ),
    ]
