# Generated by Django 6.0.1 on 2026-07-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_whatsappmessagestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappchat',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='whatsapp_attachments/'),
        ),
        migrations.AddField(
            model_name='whatsappchat',
            name='attachment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappchat',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
