# Generated by Django 6.0.1 on 2026-08-04 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_whatsappchat_attachment_whatsappchat_attachment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(choices=[('Morning', 'Morning (10 AM - 12 PM)'), ('Afternoon', 'Afternoon (12 PM - 4 PM)'), ('Evening', 'Evening (4 PM - 7 PM)')], max_length=20)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.customer')),
                ('whatsapp_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.whatsapplead')),
            ],
        ),
    ]
