# Generated by Django 6.0.1 on 2026-08-26 13:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_scheduledappointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('experience_type', models.CharField(choices=[('fresher', 'Fresher'), ('experienced', 'Experienced')], default='fresher', max_length=20)),
                ('total_experience', models.CharField(blank=True, help_text='e.g. 2 years 3 months', max_length=50)),
                ('reference_name', models.CharField(blank=True, max_length=200)),
                ('position_applied', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending (Link Sent)'), ('submitted', 'Submitted'), ('user_created', 'User Account Created')], default='pending', max_length=20)),
                ('link_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_onboardings', to=settings.AUTH_USER_MODEL)),
                ('created_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_source', to=settings.AUTH_USER_MODEL)),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidate Onboarding',
                'verbose_name_plural': 'Candidate Onboardings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('marital_status', models.CharField(blank=True, max_length=30)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('personal_mobile', models.CharField(blank=True, max_length=15)),
                ('permanent_address', models.TextField(blank=True)),
                ('permanent_city', models.CharField(blank=True, max_length=100)),
                ('permanent_state', models.CharField(blank=True, max_length=100)),
                ('permanent_pincode', models.CharField(blank=True, max_length=10)),
                ('current_address', models.TextField(blank=True)),
                ('current_city', models.CharField(blank=True, max_length=100)),
                ('current_state', models.CharField(blank=True, max_length=100)),
                ('current_pincode', models.CharField(blank=True, max_length=10)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50)),
                ('qualification', models.CharField(blank=True, max_length=100)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('passing_year', models.CharField(blank=True, max_length=10)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('percentage_cgpa', models.CharField(blank=True, max_length=20)),
                ('previous_company', models.CharField(blank=True, max_length=200)),
                ('previous_designation', models.CharField(blank=True, max_length=100)),
                ('previous_salary', models.CharField(blank=True, max_length=50)),
                ('previous_experience_duration', models.CharField(blank=True, max_length=50)),
                ('reason_for_leaving', models.TextField(blank=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=20)),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('aadhar_file', models.FileField(blank=True, null=True, upload_to='onboarding/documents/')),
                ('pan_file', models.FileField(blank=True, null=True, upload_to='onboarding/documents/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='onboarding/documents/')),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='onboarding/photos/')),
                ('educational_certificate', models.FileField(blank=True, null=True, upload_to='onboarding/documents/')),
                ('experience_letter', models.FileField(blank=True, null=True, upload_to='onboarding/documents/')),
                ('other_document', models.FileField(blank=True, null=True, upload_to='onboarding/documents/')),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_holder_name', models.CharField(blank=True, max_length=200)),
                ('account_number', models.CharField(blank=True, max_length=30)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('account_type', models.CharField(blank=True, help_text='Savings / Current', max_length=20)),
                ('declaration_accepted', models.BooleanField(default=False)),
                ('declaration_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='core.candidateonboarding')),
            ],
            options={
                'verbose_name': 'Onboarding Submission',
                'verbose_name_plural': 'Onboarding Submissions',
            },
        ),
    ]
