# Generated by Django 6.0.1 on 2026-09-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_candidateonboarding_onboardingsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('buyer', 'Buyer / Contractor'), ('seller', 'Customer / Seller / Vendor')], db_index=True, default='buyer', max_length=20),
        ),
    ]
