# Generated by Django 6.0.1 on 2026-09-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_customer_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappchat',
            name='wamid',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
