# Generated by Django 6.0.4 on 2026-09-14 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_whatsappchat_wamid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='early_out_approval_status',
            field=models.CharField(choices=[('none', 'Not Requested'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='early_out_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_early_outs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='early_out_reason',
            field=models.TextField(blank=True, help_text='Reason submitted by employee for early punch-out.', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='early_out_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='early_out_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('half_day', 'Half Day'), ('absent', 'Absent'), ('on_leave', 'On Leave'), ('holiday', 'Holiday')], default='present', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('casual', 'Casual Leave'), ('sick', 'Sick Leave'), ('earned', 'Earned Leave'), ('half_day', 'Half Day')], default='casual', max_length=20),
        ),
        migrations.CreateModel(
            name='MissedPunchOutRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missed_date', models.DateField(help_text='The date on which punch-out was missed.')),
                ('reported_exit_time', models.TimeField(help_text='Exit time reported by the employee.')),
                ('reason', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False, help_text='Admin has acknowledged this record.')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_missed_punchouts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missed_punchouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Missed Punch-Out Record',
                'verbose_name_plural': 'Missed Punch-Out Records',
                'ordering': ['-missed_date'],
            },
        ),
    ]
