# Generated by Django 6.0.4 on 2026-09-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_attendance_early_out_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappchat',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
