# Generated by Django 6.0.4 on 2026-09-17 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_whatsappchat_is_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerOnboardingTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostinger_user_id', models.IntegerField(db_index=True, help_text='Hostinger User ID (users.id)', unique=True)),
                ('onboarding_status', models.CharField(choices=[('registered', 'Registered'), ('documents_verified', 'Documents Verified'), ('approved', 'Approved'), ('onboarded', 'Onboarded')], db_index=True, default='registered', help_text='Seller onboarding lifecycle status', max_length=30)),
                ('catalogue_status', models.CharField(choices=[('pending', 'Pending'), ('data_collection', 'Data Collection'), ('data_entry', 'Data Entry'), ('seller_confirmation', 'Seller Confirmation'), ('live', 'Live')], db_index=True, default='pending', help_text='Catalogue onboarding lifecycle status', max_length=30)),
                ('welcome_whatsapp_sent', models.BooleanField(default=False)),
                ('welcome_whatsapp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('welcome_whatsapp_error', models.TextField(blank=True, null=True)),
                ('welcome_email_sent', models.BooleanField(default=False)),
                ('welcome_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('welcome_email_error', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_sellers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller Onboarding Tracker',
                'verbose_name_plural': 'Seller Onboarding Trackers',
                'ordering': ['-updated_at'],
            },
        ),
    ]
