# Generated by Django 6.0.4 on 2026-09-18 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_leadreassignmentrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppQuickReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Template title e.g. 'Seller Onboarding Welcome'", max_length=150)),
                ('keyword', models.CharField(db_index=True, help_text="Trigger shortcut without spaces e.g. 'seller', 'catalog', 'bank' (type /keyword in chat)", max_length=50, unique=True)),
                ('content_type', models.CharField(choices=[('text', 'Text Only'), ('image', 'Image + Text'), ('multiple_images', 'Multiple Images + Text'), ('document', 'Document + Text'), ('video', 'Video + Text')], default='text', max_length=20)),
                ('message', models.TextField(blank=True, default='', help_text='Formatted message/caption. Supports *bold*, _italic_, ~strike~, code, and placeholders: {{customer_name}}, {{company_name}}, {{phone}}, {{city}}')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_replies_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WhatsApp Quick Reply',
                'verbose_name_plural': 'WhatsApp Quick Replies',
                'ordering': ['keyword'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppQuickReplyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='whatsapp_templates/%Y/%m/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Video')], default='image', max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quick_reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='core.whatsappquickreply')),
            ],
            options={
                'verbose_name': 'Quick Reply Media',
                'verbose_name_plural': 'Quick Reply Media Files',
                'ordering': ['order', 'id'],
            },
        ),
    ]
