# Generated by Django 6.0.4 on 2026-10-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_customerfolder_customerfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappquickreply',
            name='meta_template_names',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of approved Meta Template names to send along with this quick reply.'),
        ),
    ]
