# Generated by Django 6.0.1 on 2026-07-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('store_name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('street_address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('website_url', models.URLField(blank=True, max_length=500, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('enrichment_status', models.CharField(choices=[('PENDING', 'Pending Enrichment'), ('SCRAPED_SUCCESS', 'Enrichment Successful'), ('SCRAPED_FAILED', 'Enrichment Failed'), ('NO_WEBSITE', 'No Website Available')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
