# Generated by Django 6.0.1 on 2026-07-17 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_network', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='osm_id',
            new_name='place_id',
        ),
    ]
