# Generated by Django 6.0.1 on 2026-09-03 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_network', '0002_rename_osm_id_vendorprofile_place_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorprofile',
            options={'ordering': ['-updated_at', '-id']},
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vendors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='searched_vendors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='party_type',
            field=models.CharField(choices=[('SELLER', 'Customer / Seller / Vendor'), ('BUYER', 'Buyer / Contractor')], db_index=True, default='SELLER', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='user_ratings_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='enrichment_status',
            field=models.CharField(choices=[('PENDING', 'Pending Enrichment'), ('SCRAPED_SUCCESS', 'Enrichment Successful'), ('SCRAPED_FAILED', 'Enrichment Failed'), ('NO_WEBSITE', 'No Website Available'), ('VERIFIED', 'Verified / Active'), ('CONTACTED', 'Contacted / Pitch Made'), ('CONVERTED', 'Converted to Customer')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='vendorprofile',
            index=models.Index(fields=['created_by', 'party_type'], name='vendor_netw_created_fec6e6_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorprofile',
            index=models.Index(fields=['assigned_to', 'party_type'], name='vendor_netw_assigne_3335ea_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorprofile',
            index=models.Index(fields=['category', 'city'], name='vendor_netw_categor_eec9a3_idx'),
        ),
    ]
