<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9">
    <xsl:output method="html" encoding="UTF-8" indent="yes" />

    <xsl:template match="/">
        <html lang="en">
        <head>
            <title>XML Sitemap</title>
            <style>
                body {
                    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
                    color: #333;
                    margin: 0;
                    padding: 40px;
                    background-color: #f8f9fa;
                }
                .container {
                    max-width: 1000px;
                    margin: 0 auto;
                    background: #fff;
                    padding: 30px;
                    box-shadow: 0 4px 15px rgba(0,0,0,0.05);
                    border-radius: 8px;
                }
                h1 {
                    font-size: 24px;
                    margin-bottom: 10px;
                    font-weight: 600;
                }
                p.desc {
                    color: #666;
                    margin-bottom: 25px;
                    font-size: 14px;
                }
                table {
                    width: 100%;
                    border-collapse: collapse;
                    font-size: 14px;
                }
                /* THE GREEN HEADER LIKE YOUR IMAGE */
                th {
                    background-color: #B70000; /* AstroTalk Green color */
                    color: #fff;
                    text-align: left;
                    padding: 12px 15px;
                    font-weight: 600;
                    text-transform: uppercase;
                    font-size: 12px;
                    letter-spacing: 0.5px;
                }
                td {
                    padding: 12px 15px;
                    border-bottom: 1px solid #eee;
                    color: #555;
                }
                tr:hover td {
                    background-color: #f9fdf0; /* Light green hover effect */
                }
                a {
                    color: #2c3e50;
                    text-decoration: none;
                    font-weight: 500;
                }
                a:hover {
                    color: #B70000;
                    text-decoration: underline;
                }
                .footer {
                    margin-top: 20px;
                    font-size: 12px;
                    color: #999;
                    text-align: center;
                }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>XML Sitemap Index</h1>
                <p class="desc">
                    This sitemap contains <xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap) + count(sitemap:urlset/sitemap:url)"/> URLs.
                </p>

                <table>
                    <thead>
                        <tr>
                            <th width="70%">URL</th>
                            <th width="30%">Last Updated</th>
                        </tr>
                    </thead>
                    <tbody>
                        <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                            <tr>
                                <td>
                                    <a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
                                </td>
                                <td>
                                    <xsl:value-of select="substring(sitemap:lastmod, 0, 11)"/> 
                                    <span style="color:#aaa; font-size:11px; margin-left:5px;">
                                        <xsl:value-of select="substring(sitemap:lastmod, 12, 5)"/>
                                    </span>
                                </td>
                            </tr>
                        </xsl:for-each>

                        <xsl:for-each select="sitemap:urlset/sitemap:url">
                            <tr>
                                <td>
                                    <a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
                                </td>
                                <td>
                                    <xsl:value-of select="substring(sitemap:lastmod, 0, 11)"/>
                                </td>
                            </tr>
                        </xsl:for-each>
                    </tbody>
                </table>
                <div class="footer">
                    Generated by Django
                </div>
            </div>
        </body>
        </html>
    </xsl:template>
</xsl:stylesheet>