# Generated by Django 6.0.4 on 2026-09-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_employee_active',
            field=models.BooleanField(default=True, help_text='If unchecked, employee cannot access the CRM portal.'),
        ),
    ]
