name: Deploy CRM to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 194.238.18.50
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/apnifactory-crm
            git pull origin master
            source myenv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart apache2